micronaut:
  application:
    name: Kafka Topology Builer API
    topology: topologies/topology-for-cloud.yaml
  topology_builder:
    brokers_list: "localhost:9092"
    allow_delete: true
    admin_config_file: "admin.properties"
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
